### ISSUE TITLE
电子围栏订阅功能

### ISSUE THREAD

**Issue by labelCS** [SVADemoAPP/Server#5]
* 完成电子围栏区域录入界面，区域范围定义从店铺范围中选择，电子围栏消息录入支持<b>文字、图片、视屏录入</b>
* 实现电子围栏区域信息的<b>增删改查</b>
* 实现电子围栏区域<b>订阅</b>与<b>取消订阅</b>

![default](https://cloud.githubusercontent.com/assets/19773167/16256843/6a7b19ea-3887-11e6-9d9b-730f8b19f3fb.png)

**Comment by wwx283823** [comment]
已完成
